[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true 


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# [etherscan]
# sepolia = "${ETHERSCAN_API_KEY}"




